src/index.html

The `import` statement is trying to get the `index.css` file but the name of the file in the example is `main.css`

Typo error in the main.js example

---

src/docs/transforms.md

@devongovett Wow. Amazing project! Also focusing on PostCSS is neat =^_^=.
Small fix for `browsers` option. We don’t recommend to use them, since not only Autoprefixer need target browsers. ESLint/Stylelint plugins, cssnano, cssnext, next `babel-preset-env` 2.0 could read browsers from one config file: [.browserslistrc](https://github.com/ai/browserslist).
We recommend only this way. Seems like you wrote this option to show options syntax. So I changed the option to `grid`.

Use recommended way to specify Autoprefixer’ browsers

---

src/index.html

Hi there, love the project ❤️ 
Just noticed there's no meta tags on the website though and figured this was something small but important I could maybe help a little with. I've run the code in this PR through [Twitter's card testing tool](https://cards-dev.twitter.com/validator) and here's how it came out.
It's possible to do more than this with these tags but I thought I'd try the quick fixes first! 😇

Add card meta tags

---

src/docs/how_it_works.md
src/docs/packagers.md

As I was reading the great documentation, I encountered a few typos/copy paste issues. I fixed these minor issues according to my native speaker ear and programmer gut.

Fix minor typos encountered while reading

---

src/docs/transforms.md

Updated the https://parceljs.org/transforms.html#postcss to have the missing colon in the .postcssrc sample code.

Added missing colon in the .postcssrc JSON

---

src/docs/code_splitting.md

Add babel polyfill to fix "ReferenceError: regeneratorRuntime is not defined" when using async/await syntax.
Thanks @thejameskyle for the corrections. We still need babel-polyfill right? Tell me if it's worth mentioning this in the docs

add babel polyfill for async/await syntax

---

src/layout/assets/style.css

box-sizing: border-box needs to be inherited on all elements, otherwise ending up with overflow issues.

Fix overflow; box-sizing on all elements

---

src/docs/production.md

I think it would help a lot of developer to add this to the documentation, in stead of showing it by the `-h` command.

Add destination folder example

---

src/docs/production.md

It took a while for me to find where the --public-url option was.
I propose like this:
When it comes time to bundle your application for production, you can use Parcel's production mode.
```bash
parcel build entry.js
```
This disables watch mode and hot module replacement so it will only build once. It also enables the minifier for all output bundles to reduce file size. The minifiers used by Parcel are [uglify-js](https://github.com/mishoo/UglifyJS2/) for JavaScript, [cssnano](http://cssnano.co) for CSS, and [htmlnano](https://github.com/posthtml/htmlnano) for HTML.
Enabling production mode also sets the `NODE_ENV=production` environment variable. Large libraries like React have development only debugging features which are disabled by setting this environment variable, which results in …

show build options, reorder text

---

src/docs/assets.md

SCSS was not documented on the website. Users had problems integrating Parcel with SCSS.
Example issue: [[Question] Can I use SCSS with parcel? #60](https://github.com/parcel-bundler/parcel/issues/60)
Add SCSS documentation to the website
Run the website, or:
I add a screenshot here for convenience.
Misleading documentation hurts users. I created an example project following the new documentation and it works. *Risk is negligible*.
Example project: [Parcel bundler SCSS example](https://github.com/gulyasm/parcel-scss-example)

Adds SCSS documentation to Assets

---

src/server.js

This let contributors test the language they are translating using query strings (eg. `localhost:5000/?locale=ru`).

Fix language selection using subdomains on localhost

---

src/i18n/pl/index.html

Polish subheader has a typo.
You could trust me about this because I used to be a full-time printed media journalist for a year but perhaps a dictionary link will be even better: https://sjp.pwn.pl/sjp/;2490229

fix: typo in polish subheader

---

src/i18n/ru/index.html

No hyphen is required in case of “молниеносно быстрый”. See http://therules.ru/hyphen-adjectives/#81.

ru-RU: remove an odd hyphen

---

now.json

This complements #87 with the fix to add the alias for the Spanish website URL.

Add alias for website in Spanish

---

src/i18n/zh/index.html

Here the 「时间」is literal translation for "time". The whole phase's so awkward while reading. The actually meaning here for the "time" is 「用时」.

improve the chinese translation

---

.gitignore
package.json

Now recently flipped their downloads to pull from GitHub instead of their CDN. The `8.5.4` download is now failing through their CDN (gzip decompression, anyway). Going ahead and upgrading.
Related:
https://github.com/zeit/now-cli/pull/1089
https://github.com/zeit/now-cli-releases/pull/4
closes #97

Update `now` to ^9.2.7

---

src/i18n/en/layout/page.html
src/i18n/es/layout/page.html
src/i18n/ko/layout/page.html
src/i18n/pl/layout/page.html
src/i18n/pt/layout/page.html
src/i18n/ru/layout/page.html
src/i18n/zh/layout/page.html

The navbar link activation doesn't work with an anchor in the URL, because the URL obtained with `window.location.href` is different of every `nav a[href]` values.
> Before:
>
> <img src="https://i.imgur.com/jODNuq6.png" width="400">
> After:
>
> <img src="https://i.imgur.com/fYoZJDi.png" width="400">

Fix error with links activation

---

src/i18n/en/docs/getting_started.md

This is not an obvious result to me, I think it should be noted in the first-run documentation.

Note that HMR can fail based on editor save-mode

---

src/i18n/en/docs/api.md

Not sure why this part of code was wrapped into an async function. Seemed unnecessary to me.
Will update other languages this is agreed upon

Remove async start function from middleware example

---

src/i18n/fr/docs/api.md
src/i18n/fr/docs/recipes.md

1. Minor fix for a phrase on recipes.md (parcel-bundler/website@95e307d04235fed7682d4131a8e8652de780ce75)
2. Remove async start function from middleware example (parcel-bundler/website@f3c4de1e61867b76e38e1c596c2e406e00586b0f)

Update translation in french

---

src/i18n/es/docs/getting_started.md

Fixed a translation error in the file es/getting_started.md

Fix spanish translation

---

src/i18n/en/docs/hmr.md

In general, it would be necessary to remove .\*.html and replace by *.md for the 4 added links

Fix hmr.md links

---

src/i18n/en/docs/api.md

The code block for using the API did not have the word function in `async function runBundle`. It now runs if copy/pasted

Add `function`

---

src/assets/style.css

The links in the `<code>` tag are not visually highlighted. This PR does the necessary to improve this.

Highlight links in <code>

---

src/i18n/en/docs/cli.md

`experimental-scope-hoisting` is supported only build mode.

Fix experimental-scope-hoisting document

---

src/assets/style.css
src/i18n/en/docs/production.md

Adds a short documentation about the new file naming strategy, based on @jamiebuilds table in https://github.com/parcel-bundler/parcel/pull/1025
Related #132

Add filename strategy doc

---

src/i18n/en/docs/recipes.md
src/i18n/en/docs/transforms.md

Updates babel transforms doc to include defaults and basic introduction to how we use `babel-preset-env`
This also removes the redundant `babel-preset-env` from Preact example
Closes #175

update babel part in transforms

---

src/i18n/en/docs/production.md

I was showing a few weird errors on my CI log when building for production because I did not have `lscpu` available and it took me a few minutes to figure out.
I thought it would be helpful to add some docs about that.

Add docs about `lscpu` to "production" section

---

src/i18n/en/docs/asset_types.md
src/i18n/en/docs/packagers.md

This might sound silly, but I got stuck for over an hour trying to figure out what was going on with the exports. From the example, I assumed the worker process automagically extracted the class with some other mechanism.

Add export to asset types example

---

src/i18n/en/docs/plugins.md

Scoped plugin names `@your-scope/parcel-plugin` is supported but not mentioned in the docs, let's do that.

Inform of scoped plugin name support

---

src/i18n/en/docs/assets.md

The beginnings of a Default Assets section as raised in https://github.com/parcel-bundler/website/issues/198
I've omitted a column for configuration suggested in #198 as I feel sections for each type might better explain the configuration available, how the configuration is defined, limitations, caveats, associated transforms etc.

document default supported assets

---

build.sh

specifically:
> [shellcheck] Double quote to prevent globbing and word splitting. [SC2086]

fix shellcheck error

---

src/i18n/en/docs/env.md
src/i18n/en/layout/page.html

This is my suggestion for documenting `.env` support https://github.com/parcel-bundler/parcel/pull/258.
The original suggestion https://github.com/parcel-bundler/website/issues/216 was for this to be listed under the
>advanced section
but most of the advanced section is about authoring plugins/packagers and using the direct api. I thought keeping it alongside the usage explanation, namely post Code Splitting, a better fit.
I may raise an issue in the future to discuss reorganising the documentation as I've found it difficult for a number of reasons in the past.

document env file support

---

src/i18n/en/docs/api.md

* **Added** the `hmr` option to the `API` document since it was missing.

added missing `hmr` option to API documentation

---

src/i18n/en/docs/module_resolution.md
src/i18n/en/layout/page.html

This is my initial attempt at resolving https://github.com/parcel-bundler/website/issues/184, https://github.com/parcel-bundler/website/issues/132 and documenting https://github.com/parcel-bundler/parcel/pull/850
I have a few questions which I believe should be answered and better described before merging:
- I would like to answer this question in the docs https://github.com/parcel-bundler/parcel/pull/850#issuecomment-372105317
- clarify terminology of:
- project root: top-level package.json?
- package root: package.json in node_module module? where does this start to resolve from?
- these comments https://github.com/parcel-bundler/parcel/pull/850/files#diff-f90b0caefa8028ff5ec8f2f2c2e6e39dR8 seem to suggest I may be missing some important information that should be documented
Closes #184

document module resolution strategies

---

src/i18n/en/docs/transforms.md
src/i18n/es/docs/transforms.md
src/i18n/fr/docs/transforms.md
src/i18n/it/docs/transforms.md
src/i18n/ko/docs/transforms.md
src/i18n/pl/docs/transforms.md
src/i18n/pt/docs/transforms.md
src/i18n/ru/docs/transforms.md
src/i18n/zh/docs/transforms.md

I saw that the parcel itself has been [updated](https://github.com/parcel-bundler/parcel/blob/master/package.json#L18-L29) to use the most recent babel version with scoped packages so I have attempted to mirror it in the docs as well.
The languages I don't speak I changed the preset names and for Russian doc I've updated the documentation to match the english version

Update babel notes to use scoped package names

---

src/i18n/pt/docs/getting_started.md

Fixing typo for "diretorio" and translate the "Building for production" title for pt lang.

Fixing "getting started" documentation for pt lang

---

src/i18n/en/docs/cli.md
src/i18n/es/docs/production.md
src/i18n/fr/docs/cli.md
src/i18n/pt/docs/cli.md
src/i18n/pt/docs/production.md

Update for consistency with parcel-bundler/parcel#1846

Fix public-url option

---

src/i18n/en/docs/assets.md

See https://github.com/parcel-bundler/parcel/pull/1732

Add usage examples for HTML bundle loader

---

src/i18n/en/docs/cli.md

Allows for a more concious choice of export.
I use parcel to bundle npm libraries, discovering "dependencies" are not bundled in "node" export mode was of great use :)

Added infos about cli's "--target" flag regarding package bundling

---

src/i18n/en/docs/recipes.md
src/i18n/pt/docs/recipes.md

Complementing [recipes](https://pt.parceljs.org/recipes.html) documentation with the newer contents of english docs.
Fix markdown style in english documentation (using markdown lint to remove/add spaces when necessary).

Sync 'recipes' documentation for pt lang

---

src/i18n/en/docs/production.md

Hi! I was trying to use Parcel with Netlify's build agent and had to do it as described in my change to the Production doc. I wondered if this information might be useful for other people.
I'm sorry I'm not able to localise the text.

Added info about running Parcel without installing it globally

---

src/i18n/en/docs/transforms.md

* Updates the Transforms page to be consistent with https://github.com/parcel-bundler/parcel/pull/559 and https://github.com/parcel-bundler/parcel/pull/1101.
* Adds a link from the Transforms page to the Babel section of the JavaScript page. (I originally arrived to the Parcel documentation specifically curious about how Parcel handled Babel, and the "Transforms" page seemed to be the page most specifically about Babel, so I incorrectly assumed the rest of the documentation didn't have anything more detailed about Babel. I think this link would have helped me out.)

Update description of node_modules handling

---

src/i18n/en/docs/html.md
src/i18n/es/docs/transforms.md
src/i18n/fr/docs/html.md
src/i18n/it/docs/transforms.md
src/i18n/ko/docs/transforms.md
src/i18n/pl/docs/transforms.md
src/i18n/pt/docs/html.md
src/i18n/ru/docs/transforms.md
src/i18n/uk/docs/transforms.md
src/i18n/zh-tw/docs/html.md
src/i18n/zh/docs/transforms.md

The documented `posthtmlrc.js` does not work; only when `.posthtmlrc.js` is used is the configuration recognised.
This is confirmed by the source code for `parcel` at https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/posthtml.js#L29

Corrected name of .posthtmlrc.js

---

src/i18n/en/docs/scss.md

Add additional information related SCSS asset type and modify the installation command for `sass` module. The module should be installed as a dev dependency instead of normal dependency.

Update for SCSS asset type page

---

src/i18n/en/docs/api.md

The old wording of this line made it sound like sourcemaps weren't supported in minified builds.
(Normally I'd try to make my PRs more substantial, but this line nearly scared me off of Parcel before I thought to try it, so I figured tweaking it was important enough for a small PR.)

Nit: Improve wording of sourceMaps option

---

src/i18n/en/docs/module_resolution.md

Not sure if it is a typo since that anchor on my own Chrome Browser is broken.

Fix a certain typo

---

src/i18n/en/docs/module_resolution.md

I wanted to explain to a colleague how the module resolution in Parcel worked today, but couldn't find any info.
I expanded on some of the points in [Resolver.js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Resolver.js), and linked to the Node docs.

Docs: Link node resolution + docs from Resolver.js

---

src/i18n/en/docs/api.md

noticed the `--global` option is documented for the CLI, but not the JS API. This PR adds the `global` field to the list of documented options for the JS API.

document global option for bundler

---

src/i18n/en/docs/module_resolution.md

The words "project root" imply that this is the root of the whole project, i.e. where package.json is located. I think renaming it to "entry root" would be less confusing, because I got confused by the naming and lost some time debugging.

Clarify docs by replacing "project root" with "entry root"

---

src/server.js

Currently, if switching to a translation which doesn't have page that corresponds to the current page, an error is printed.
Fixup for #338

Redirect to homepage if page is not found

---

src/i18n/en/docs/api.md
src/i18n/en/docs/cli.md

Update API & CLI documentation to reflect existing log levels

---

src/i18n/fr/docs/api.md
src/i18n/fr/docs/cli.md
src/i18n/fr/docs/module_resolution.md
src/i18n/fr/docs/typeScript.md

1. Document global option for bundler (parcel-bundler/website@1cf57ae53c4ede81029a08e4bd789b5b1cafdd16)
2. Replace "project root" with "entry root" (parcel-bundler/website@e13ef4004ae1ea2d75ba85bbac5213ce1a8b262f)
3. Update typeScript.md (parcel-bundler/website@027f232e451a0061121ee704b5f78ff16fe007b0)
4. Update API & CLI documentation to reflect existing log levels (parcel-bundler/website@c185d811538567a98de85205c2aa77cb67a89891)

Sync docs FR

---

src/i18n/en/docs/code_splitting.md

Wasn't sure how this was working, or whether I needed to configure anything.
Thanks to this issue for the info: https://github.com/parcel-bundler/parcel/issues/2433

bundle resolution in code splitting

---

src/assets/icon-elm.svg
src/i18n/en/docs/elm.md
src/i18n/en/layout/page.html

While Parcel has a stellar support fort Elm language right out of the box, there is no mention of this feature in the official documentation. This PR should fix that.
The Elm logo was taken from the [elm/foundation.elm-lang.org](https://github.com/elm/foundation.elm-lang.org) repository.

Add Elm language support documentation.

---

src/i18n/en/docs/getting_started.md

Using the word "just" before an instruction can feel belittling:
http://bradfrost.com/blog/post/just/

Remove the word "just"

---

src/i18n/en/index.html

Thought the intention was probably to demonstrate how easy the process is, using the word "just" can be dismissive and make people feel bad:
http://bradfrost.com/blog/post/just/

Remove the word "just" from instructions

---

src/i18n/en/layout/page.html
src/i18n/es/layout/page.html
src/i18n/fr/layout/page.html
src/i18n/it/layout/page.html
src/i18n/ko/layout/page.html
src/i18n/pl/layout/page.html
src/i18n/pt/layout/page.html
src/i18n/ru/layout/page.html
src/i18n/uk/layout/page.html
src/i18n/zh-tw/layout/page.html
src/i18n/zh/layout/page.html

Include Japanese into the language list shown in individual pages.
Before:
After:
Follow up to #382.

Add Japanese to language list in layout

---

README.md

Add all locals links to README.md

#406 added links to README.md

---

src/i18n/en/docs/recipes.md

Consistency makes things easier to read. This is trivial but (I hope) a no brainer.
NB. Related, it's worth noting that the [yarn docs](https://yarnpkg.com/lang/en/docs/cli/add/) actually show the --flags at the end of the command, so maybe this usage is (consistently) wrong?

Trivial: make usage of `--dev` flag consistent

---

src/i18n/en/docs/cli.md
src/i18n/en/docs/css.md
src/i18n/en/docs/elm.md
src/i18n/en/docs/getting_started.md
src/i18n/en/docs/javascript.md
src/i18n/en/docs/module_resolution.md
src/i18n/en/docs/production.md
src/i18n/en/docs/pug.md
src/i18n/en/docs/typeScript.md
src/i18n/en/docs/vue.md
src/i18n/ja/docs/transforms.md
src/i18n/pt/docs/api.md
src/i18n/pt/docs/cli.md
src/i18n/pt/docs/code_splitting.md
src/i18n/pt/docs/coffeeScript.md
src/i18n/pt/docs/css.md
src/i18n/pt/docs/elm.md
src/i18n/pt/docs/getting_started.md
src/i18n/pt/docs/javascript.md
src/i18n/pt/docs/module_resolution.md
src/i18n/pt/docs/production.md
src/i18n/pt/docs/pug.md
src/i18n/pt/docs/stylus.md
src/i18n/pt/docs/typeScript.md
src/i18n/pt/docs/vue.md
src/i18n/pt/layout/page.html

Sending some changes to synchronize the documentation in portuguese with that which is available in english. 📝 While I did this, I also altered some simple things in the markdown of the documentation files in english. Things like spacing, correct use of  "#" for titles, adding syntax in code blocks, etc.

Synchronizing portuguese documentation

---

src/i18n/en/docs/javascript.md

In light of https://github.com/parcel-bundler/parcel/issues/1655, I've updated this language to be more accurate to the current state of parcel.

Update language on approach to transpiling node_modules

---

src/i18n/en/docs/recipes.md
src/i18n/es/docs/recipes.md
src/i18n/fr/docs/recipes.md
src/i18n/it/docs/recipes.md
src/i18n/ja/docs/recipes.md
src/i18n/ko/docs/recipes.md
src/i18n/pl/docs/recipes.md
src/i18n/pt/docs/recipes.md
src/i18n/ru/docs/recipes.md
src/i18n/uk/docs/recipes.md
src/i18n/zh-tw/docs/recipes.md
src/i18n/zh/docs/recipes.md

For Preact, installing `babel-core` and `babel-preset-preact` is unnecessary in the current version.

Update Preact section in recipes.md

---

src/i18n/en/docs/scss.md

Parcel's [Getting Started documentation ](https://parceljs.org/getting_started.html) includes both yarn and npm installation instructions. 
To maintain consistency with that pattern, this update adds  yarn-specific installation instructions to the [Parcel SCSS page](https://parceljs.org/scss.html).

Add yarn instructions

---

src/i18n/en/docs/vue.md

Vue component files normally start with a capital letter (`App.vue`, `HelloWorld.vue`).
Also, `import` and `export` statements are normally separated with a space to increase readability

Improved some readability

---

src/i18n/en/docs/typeScript.md

These are common pain points for users.
I would recommend the parcel-plugin-typescript, but it does not work with recent versions (>1.9, maybe?) of parcel-bundler.

typescript: document type checking and baseUrl

---

src/i18n/en/docs/toml.md

Adds a simple TOML example shamelessly based on the YAML one. (something’s better than nothing right?)

adds TOML documentation

---

src/i18n/en/docs/env.md

Noticed this was a bit unclear and sunk some time into debugging why `console.log(process.env)` wasn't showing any values until I found the [referenced issue](https://github.com/parcel-bundler/parcel/issues/2299). Hopefully this will save someone time in the future :)

Clarify process.env caveat in documentation

---

src/i18n/en/docs/api.md

Found available option inside https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Bundler.js#L144-L149

Add "autoInstall" documentation

---

src/i18n/zh/docs/hmr.md

Make module-re-evaluation in HMR easier to understand.
And the en version:
> The new code then replaces the old version, and is re-evaluated along with all parents.

Update hmr.md in zh-CN

---

src/i18n/zh/docs/api.md

`browser` is a parameter value. (No need to translate.)

docs(api.md): `target` ZH_CN

---

README.md
src/i18n/en/index.html
src/i18n/en/layout/page.html
src/i18n/es/index.html
src/i18n/es/layout/page.html
src/i18n/fr/index.html
src/i18n/fr/layout/page.html
src/i18n/it/index.html
src/i18n/it/layout/page.html
src/i18n/ja/index.html
src/i18n/ja/layout/page.html
src/i18n/ko/index.html
src/i18n/ko/layout/page.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/pt/layout/page.html
src/i18n/ru/index.html
src/i18n/ru/layout/page.html
src/i18n/uk/index.html
src/i18n/uk/layout/page.html
src/i18n/zh-tw/index.html
src/i18n/zh-tw/layout/page.html
src/i18n/zh/index.html
src/i18n/zh/layout/page.html

Hello!
First of all thank you for parcel, love it!
I noticed a typo in language picker on the parcel website for Polish language. It should be `Polski` instead of `Polskie`. Im a native speaker so I instantly spotted this tiny mistake.
This PR fixes this typo.

Fix typo in language picker: Polskie -> Polski

---

src/i18n/en/docs/recipes.md

Added setup steps for Svelte in-line with the existing content for React, Preact, Vue, etc.
Added to bottom but suggest it's pulled up to show next to the other frameworks.

Update recipes.md with setup for Svelte

---

src/i18n/ko/layout/page.html

I'm korean developer using and interested in parcel-bundler.
I found that search input placeholder is not according to Korean meaning.
`검색` is more in korean meaning than `수색`.
Review my PR for more korean developers using parcel-bundler.
Thanks.

Replace placeholder according to Korean meaning

---

src/i18n/ko/docs/code_splitting.md

Adding bundle-resolution content in Korean.
It isn't added in Korean documentation. So, I translate Korean in english code-splitting document.
Please check this translation.
Thank you.

Add bundle-resolution in code-splitting document

---

src/i18n/en/docs/vue.md

Upon following this guide I realized an error with the previous `new Vue(App).$mount('#app');` line. After some searching I found the `createElement` alternative which works without error.

Updated `new Vue()` line with `createElement()`

---

src/i18n/en/docs/module_resolution.md

Fix typo for npm organizations. When I translate page module-resolution in Korean, I found the word organisation. So, I found [npm page](https://www.npmjs.com/), They named **npm organization**. 
It could be correct organisations word, So If correct, I will close this pull request.
Thank you. :)

Fix typo npm organizations

---

src/i18n/en/docs/typeScript.md

When setting up HMR, the TypeScript compiler would complain as it isn't aware of Parcel's module API. To fix this, types has been added ([see this issue](https://github.com/parcel-bundler/parcel/issues/1063)).
This PR updates the docs so that people are aware of this and don't end up getting the same error.

Update docs to mention required TypeScript types

---

src/i18n/en/index.html

I've replaced the 👌 [ok hand] emoji in the *[Hello World](https://parceljs.org/)* section with a 👍[thumbs up] emoji.
The reasoning behind this change is to remove harmful
language from the documentation:
> The hand gesture has been used by White Supremacists
> as a dogwhistle to identify other White Supremacists 
> at rallies, in forums, and even at court hearings. 
> In 2019, the hand gesture was added to the 
> Anti-Defamation League's list of official symbols 
> of hate.
>
> [👌 [ok hand] at Self-Defined](https://www.selfdefined.app/#ok-hand)

Improve use of inclusive language

---

src/i18n/en/docs/pug.md

According to the file structure example it should be `style.css`, not `index.css`.

fix misspelling

---

src/i18n/en/docs/openGL.md

The sample shader is a fragment shader, not a vertex shader.

Correct heading in OpenGL.md

---

src/i18n/zh/docs/javascript.md

The removed sentence means:
> Translator's note: Flow is dead. Now is the world of TypeScript.
The sentence does not exist in neither the original en version nor other translations. It may be the translators' personal opinion, and thus does not suitable to appear in the docs.

Remove opinion-ish words in the zh-cn translation

---

src/features/module-resolution.md

The following sentence suggests that the resolution order is different when scope hoisting is is disabled:
> Without scope hoisting however, main is preferred to module for better performance:
However, the following list is identical to the previous one (if scope hoisting is enabled). I did not check the actual implementation, so changing the order in the list to match what the sentence is saying might not be the correct fix.

Fix module resolution order
