src/docs/getting_started.md

I hope these changes will make it easier for beginners to follow. I've included a step to create a package.json file, which is better to leave out if it isn't necessary (to make the process simpler for beginners) but it is necessary until https://github.com/parcel-bundler/parcel/issues/2  is addressed.
I tried to make this read more sequentially "do this, then do this" and include all the necessary steps to result in a successful Parcel project, simply by following along.
I also tweaked some of the copy in hopes of making it more clear. Feel free to ignore any/all of this or use it as a jumping off point :)

Make getting started more explicit

---

README.md
src/docs/getting_started.md

- _Contributing_ section in `README.md` with missing steps
- Add `yarn init` in _Geting started_ section in docs

Little improves in docs

---

src/docs/transforms.md

1-byte typo in transforms.md

---

src/docs/code_splitting.md

To be merged with: https://github.com/parcel-bundler/parcel/pull/78

Update dynamic import docs to clarify default imports

---

src/assets/home.css

Fix language-dropdown styles

---

src/assets/icons.js
src/i18n/en/docs/transforms.md
src/i18n/en/index.html
src/i18n/ko/index.html
src/i18n/ru/index.html
src/i18n/zh/index.html

This PR also aims to add .ts to the icon animation on the front page, though it looks like all of the icons are inside of an .svg file, and I'm not sure how to go about making a new one.
Also open to suggestions on where the docs section I added should go, if not the Transforms section (maybe Recipes?)

Add typescript info

---

now.json
src/i18n/en/index.html
src/i18n/ko/index.html
src/i18n/pl/docs/asset_types.md
src/i18n/pl/docs/assets.md
src/i18n/pl/docs/code_splitting.md
src/i18n/pl/docs/getting_started.md
src/i18n/pl/docs/hmr.md
src/i18n/pl/docs/how_it_works.md
src/i18n/pl/docs/packagers.md
src/i18n/pl/docs/plugins.md
src/i18n/pl/docs/production.md
src/i18n/pl/docs/recipes.md
src/i18n/pl/docs/transforms.md
src/i18n/pl/index.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/ru/index.html
src/i18n/zh/index.html

Fixes #73.
Comments from Polish speaking users are welcome, especially on technical terms.

Translate into Polish

---

src/i18n/en/index.html
src/i18n/zh/index.html

resolve #77 
"4 physical CPUs" -> "4 physical cores CPU"

update descript of build machine

---

src/i18n/en/docs/assets.md
src/i18n/en/docs/production.md
src/i18n/en/docs/recipes.md
src/i18n/ko/docs/assets.md
src/i18n/ko/docs/production.md
src/i18n/ko/docs/recipes.md
src/i18n/pl/docs/assets.md
src/i18n/pl/docs/production.md
src/i18n/pl/docs/recipes.md
src/i18n/pt/docs/assets.md
src/i18n/pt/docs/production.md
src/i18n/pt/docs/recipes.md
src/i18n/ru/docs/assets.md
src/i18n/ru/docs/production.md
src/i18n/ru/docs/recipes.md
src/i18n/zh/docs/assets.md
src/i18n/zh/docs/production.md
src/i18n/zh/docs/recipes.md

Fix all missing language declarations

---

src/i18n/en/docs/hmr.md

Add safe write

---

src/i18n/en/docs/production.md

Blocked untill https://github.com/parcel-bundler/parcel/pull/617 gets merged

Add disable source-maps flag to production docs

---

README.md

Adding doc session about how to change language

adding doc session about how to change language

---

src/i18n/zh/docs/api.md
src/i18n/zh/layout/page.html

update(zh-cn): translate api.md into Chinese

---

src/i18n/en/docs/transforms.md

Related issue on main repo https://github.com/parcel-bundler/parcel/issues/368

Add note about existing css libs and css modules support

---

src/i18n/en/docs/transforms.md
src/i18n/zh/docs/transforms.md

add reasonml doc (fix #61)

---

src/i18n/ko/docs/transforms.md

1. PostCSS + CSS Module + external CSS library doc
2. ReasonML/ReasonReact doc

Translation(ko) update

---

src/i18n/zh/docs/transforms.md

update the content of some transforms

update(zh-cn): translate transforms.md

---

src/i18n/en/index.html
src/i18n/es/index.html
src/i18n/ko/index.html
src/i18n/pl/index.html
src/i18n/pt/index.html
src/i18n/ru/index.html
src/i18n/zh/index.html

That isn't the English page for computers in others languages.

Fix links to the English page

---

src/i18n/en/docs/recipes.md

Following from the v1.7.0 release. I just thought I could contribute a little. Hope it's helpful!

Add Vue recipe

---

now.json
src/i18n/en/index.html
src/i18n/en/layout/page.html
src/i18n/es/index.html
src/i18n/es/layout/page.html
src/i18n/fr/docs/api.md
src/i18n/fr/docs/asset_types.md
src/i18n/fr/docs/assets.md
src/i18n/fr/docs/cli.md
src/i18n/fr/docs/code_splitting.md
src/i18n/fr/docs/getting_started.md
src/i18n/fr/docs/hmr.md
src/i18n/fr/docs/how_it_works.md
src/i18n/fr/docs/packagers.md
src/i18n/fr/docs/plugins.md
src/i18n/fr/docs/production.md
src/i18n/fr/docs/recipes.md
src/i18n/fr/docs/transforms.md
src/i18n/fr/index.html
src/i18n/fr/layout/page.html
src/i18n/ko/index.html
src/i18n/ko/layout/page.html
src/i18n/pl/index.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/pt/layout/page.html
src/i18n/ru/index.html
src/i18n/ru/layout/page.html
src/i18n/zh/index.html
src/i18n/zh/layout/page.html

French translation for the website
For ease of proofreading, I advise you to consult only the commit "Translation in french": this allows you to compare with the original language

French translation

---

src/i18n/en/docs/transforms.md

Describes `cssnano.config.js` support via https://github.com/parcel-bundler/parcel/issues/347

cssnano config doc

---

src/i18n/fr/docs/api.md
src/i18n/fr/docs/asset_types.md
src/i18n/fr/docs/assets.md
src/i18n/fr/docs/cli.md
src/i18n/fr/docs/code_splitting.md
src/i18n/fr/docs/getting_started.md
src/i18n/fr/docs/hmr.md

Several corrections following the review of @sylvainpolletvillard (#140). He did a lot of proofreading work, but there are still several files to read again.
@sylvainpolletvillard Thank you again for your work.
**This PR can be merged**

Fix typo french translation

---

src/i18n/en/docs/hmr.md

hmr: highlighting the basic values for disabling safe write

---

src/i18n/en/docs/cli.md

Improvements documentation of cli

---

src/i18n/fr/docs/api.md
src/i18n/fr/docs/cli.md
src/i18n/fr/docs/hmr.md

1. hmr: highlighting the basic values for disabling safe write (parcel-bundler/website@9922df8b1e120345861c21a64ae24d5b578cab7c)
2. Improvements documentation of cli (parcel-bundler/website@75ab5452c3e6af19105f667bf75b992ca54b8b95)
3. Little improvements of api (parcel-bundler/website@2010a2873f653b28acc768040db1b7981f6369f2)

Update translation in french

---

src/i18n/it/docs/assets.md

Minor grammatical errors in italian translation

---

src/i18n/en/index.html
src/i18n/en/layout/page.html
src/i18n/es/index.html
src/i18n/fr/index.html
src/i18n/fr/layout/page.html
src/i18n/it/index.html
src/i18n/it/layout/page.html
src/i18n/ko/index.html
src/i18n/ko/layout/page.html
src/i18n/pl/index.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/pt/layout/page.html
src/i18n/ru/index.html
src/i18n/ru/layout/page.html
src/i18n/zh/index.html
src/i18n/zh/layout/page.html

Remove national flag on language list

---

src/i18n/es/layout/page.html

Remove remaining flags from language list

---

src/i18n/en/docs/transforms.md

Updating in accordance with https://github.com/parcel-bundler/website/commit/be0d48a74a1cfe7b78497e0c85c6a93bc4d87d71

Russian translation: actualize transforms.md

---

src/i18n/en/docs/hmr.md

Adds a note to hmr about auto-install
Related to #132

Add note for parcel's auto-install feature

---

src/i18n/fr/docs/api.md

1. add: contenthash option to api options (parcel-bundler/website@81d8a547cea661d9c9ef039ee90f1882d1a1ea16)

Update translation in french (#211)

---

src/i18n/en/docs/api.md

document scopeHoist, as per conversation https://github.com/sw-yx/create-react-app-parcel/issues/17

document scopeHoist

---

src/i18n/ru/docs/cli.md

Updating in accordance with https://github.com/parcel-bundler/website/commit/06d6d0387a6148f0d1d65bb7d67ba64c3dabf4e6
Hi @sn0wil, please review this.

Russian translation: actualize cli.md

---

src/i18n/en/docs/assets.md

I added this line because as a new comer it took a while for me to figure out what to do with the buffer. I think adding this small example will help others a lot... Hope you like it.

Add method to convert image buffer into image on page

---

src/i18n/pl/docs/asset_types.md
src/i18n/pl/docs/assets.md
src/i18n/pl/docs/code_splitting.md
src/i18n/pl/docs/getting_started.md
src/i18n/pl/docs/hmr.md
src/i18n/pl/docs/how_it_works.md
src/i18n/pl/docs/plugins.md
src/i18n/pl/docs/production.md
src/i18n/pl/docs/transforms.md
src/i18n/pl/index.html

- Fix grammar issues
- Fix typos
- Update Transforms file to match English documentation

Improve Polish translation

---

src/i18n/en/docs/getting_started.md

I found that there isn't information about multiple entries, so I added. Closes #219

Add multiple entry files description

---

src/i18n/en/docs/api.md

Pretty sure there's a clearer way to describe that, but couldn't think of any. This bit would have helped me a lot, already ;)

API Docs for multiple entry files

---

src/i18n/en/index.html

primary action is on the right

swap buttons

---

src/i18n/zh/docs/api.md
src/i18n/zh/docs/cli.md
src/i18n/zh/docs/getting_started.md
src/i18n/zh/docs/transforms.md

1. Improve server middleware code example (https://github.com/parcel-bundler/website/commit/6156d395114837cd581a541a4d2312a17146bd30)
2. Fix some commands in cli (https://github.com/parcel-bundler/website/commit/03557d5d44e85fd9f3c3e8ae68abad655ed7132f)
3. Add https flag to cli (https://github.com/parcel-bundler/website/commit/3acca7a1147f175944c8c316cf50556d8fab2bba)
4. Add cssnano config doc (https://github.com/parcel-bundler/website/commit/9b346cc5deaea0d8af60b4794df3f9b99d297e1d)
5. Note that HMR can fail based on editor save-mode (https://github.com/parcel-bundler/website/commit/cac896ddad92b53122fb4ae5712f248c5e10acef)

Update translation in chinese

---

src/server.js

Thought this might help to ensure the build script is run first. I initially ran the start script and was confused by the error returned.

check for build

---

.gitignore
src/assets/style.css
src/i18n/en/layout/page.html
src/i18n/es/layout/page.html
src/i18n/fr/layout/page.html
src/i18n/it/layout/page.html
src/i18n/ko/layout/page.html
src/i18n/pl/layout/page.html
src/i18n/pt/layout/page.html
src/i18n/ru/layout/page.html
src/i18n/uk/layout/page.html
src/i18n/zh/layout/page.html

Add Algolia DocSearch

---

src/i18n/en/docs/recipes.md

Issue #60 add Typescript recipe.
How do you deal with translations, do you go with google translate until someone makes a PR ?
Let me know if you'd like some adjustments :)

Issue #60 add Typescript recipe

---

src/i18n/fr/docs/recipes.md

Added French translations for the new Typescript recipe in english docs. 
I'll do another one for the cli doc update soon :)

Sync 'recipes' documentation for FR lang

---

src/i18n/pt/docs/transforms.md

Complementing [transforms](https://pt.parceljs.org/transforms.html) documentation with the newer contents of english docs.

Sync 'transforms' documentation for pt lang

---

src/i18n/fr/docs/cli.md

Added French translations for the updated CLI english docs (--target updates & --bundle-node-modules flag).
Have a great day :)

Sync 'cli' documentation for FR lang

---

src/i18n/en/docs/html.md

I believe this should close #155. Let me know if any changes need to be made and I'll gladly update 🙂

add information about uncompiled asset links in html

---

src/i18n/en/docs/asset_types.md
src/i18n/en/index.html
src/i18n/pt/index.html

Fix dead link in asset_types.md

---

src/i18n/zh-tw/index.html

This PR updates items on footer.

Adjust links on footer (zh-tw)

---

src/i18n/en/docs/cli.md

Follow https://github.com/parcel-bundler/parcel/pull/1834
I add `verbose` and `debug` options to log level

Update log level options

---

src/i18n/en/docs/javascript.md
src/i18n/en/docs/module_resolution.md
src/server.js

* Flow section under JavaScript asset type
* Flow section in Module Resolution to demonstrate support of Absolute path mappings in `.flowconfig`

Document Flow support

---

src/i18n/pt/docs/typeScript.md

Fixed misspelling on TypeScript

---

src/i18n/zh-tw/docs/javascript.md
src/i18n/zh-tw/docs/module_resolution.md

Document Flow support (zh-tw)

---

src/i18n/pt/docs/api.md
src/i18n/pt/docs/javascript.md
src/i18n/pt/docs/less.md
src/i18n/pt/docs/scss.md
src/i18n/pt/docs/transforms.md

Updating the portuguese documentation with all changes from english docs, from latests commits.
There's a specific commit (25355bf59cac08f89441cbbab1cf145c73a6ede7) that I was confused if it is really necessary to include in the pt documentation. I don't understand very well, but will this Parcel shirt be made available for limited time sale? I noticed that on the site there is a  "8 days left".
If it is indefinitely, I think it would be nice to include in the Portuguese documentation and see people supporting the Parcel as well.

Syncing portuguese documentation with latest changes from english

---

src/i18n/zh-tw/docs/api.md
src/i18n/zh-tw/docs/javascript.md
src/i18n/zh-tw/docs/less.md
src/i18n/zh-tw/docs/scss.md
src/i18n/zh-tw/docs/transforms.md
src/i18n/zh-tw/index.html
src/i18n/zh-tw/layout/page.html

Sync changes

---

src/i18n/en/docs/css.md
src/i18n/es/docs/transforms.md
src/i18n/fr/docs/css.md
src/i18n/it/docs/transforms.md
src/i18n/ko/docs/transforms.md
src/i18n/pl/docs/transforms.md
src/i18n/pt/docs/css.md
src/i18n/ru/docs/transforms.md
src/i18n/uk/docs/transforms.md
src/i18n/zh-tw/docs/css.md
src/i18n/zh/docs/transforms.md

postcss-cssnext has been deprecated in favor of postcss-preset-env

Replaced cssnext with Preset Env

---

src/i18n/en/docs/production.md

Document development-only debugging

---

src/i18n/en/index.html
src/i18n/en/layout/page.html
src/i18n/es/index.html
src/i18n/es/layout/page.html
src/i18n/fr/index.html
src/i18n/fr/layout/page.html
src/i18n/it/index.html
src/i18n/it/layout/page.html
src/i18n/ko/index.html
src/i18n/ko/layout/page.html
src/i18n/pl/index.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/pt/layout/page.html
src/i18n/ru/layout/page.html
src/i18n/uk/layout/page.html
src/i18n/zh-tw/index.html
src/i18n/zh-tw/layout/page.html
src/i18n/zh/index.html
src/i18n/zh/layout/page.html

Hello :) 
I thought it would be nice to add the language to the html tag.
I know it is already set among the HTTP response header, however, it may be still helpful to screenreaders when saving the page offline.
Cheers!

Add missing lang attribute to <html>

---

src/i18n/en/docs/javascript.md

After the discussion in https://github.com/parcel-bundler/parcel/issues/2421

Mention importing modules from URLs

---

src/assets/home.css

fix hidden banner for small screen

---

src/i18n/fr/docs/api.md
src/i18n/fr/docs/javascript.md
src/i18n/fr/docs/module_resolution.md
src/i18n/fr/docs/production.md

1. Add note on http server in api docs (parcel-bundler/website@627c010c3055e21c2ae9c0b717c43b82f168fcd9)
2. Update module_resolution.md (parcel-bundler/website@313b1ef8dff7f28a1638762e0376eb18890f9bf1)
3. Link node resolution + docs from Resolver.js (parcel-bundler/website@495b77545d45545b938c3cbf6d00860cea34e57b)
4. Document development-only debugging (parcel-bundler/website@7af71a26b96d3bc3f4bfee58f2266d3d696fd2b9)
5. Mention importing modules from URLs (parcel-bundler/website@987e424e02ada9a46c6e5de9e02746dec45edbff)
6. Make API example comments style/syntax consistent (parcel-bundler/website@faa24df04d0e74c79577526ea051fd7828da36d7)

Sync docs FR

---

src/i18n/zh-tw/docs/api.md
src/i18n/zh-tw/docs/javascript.md
src/i18n/zh-tw/docs/module_resolution.md
src/i18n/zh-tw/docs/production.md

Sync with changes in following commits:
- 627c010c3055e21c2ae9c0b717c43b82f168fcd9
- 313b1ef8dff7f28a1638762e0376eb18890f9bf1
- 495b77545d45545b938c3cbf6d00860cea34e57b
- 7af71a26b96d3bc3f4bfee58f2266d3d696fd2b9
- 987e424e02ada9a46c6e5de9e02746dec45edbff

Sync with EN version

---

src/i18n/zh-tw/docs/api.md
src/i18n/zh-tw/docs/css.md

Sync following files with English version
- api.md
- css.md

Update api.md and css.md (zh-tw)

---

src/i18n/en/docs/typeScript.md

Additional doc for TS + React + JSX, since it doesn't work out of the box.

Update typeScript.md doc for React+JSX

---

src/i18n/en/index.html
src/i18n/en/layout/page.html
src/i18n/es/index.html
src/i18n/es/layout/page.html
src/i18n/fr/index.html
src/i18n/fr/layout/page.html
src/i18n/it/index.html
src/i18n/it/layout/page.html
src/i18n/ko/index.html
src/i18n/ko/layout/page.html
src/i18n/pl/index.html
src/i18n/pl/layout/page.html
src/i18n/pt/index.html
src/i18n/pt/layout/page.html
src/i18n/ru/index.html
src/i18n/ru/layout/page.html
src/i18n/uk/index.html
src/i18n/uk/layout/page.html
src/i18n/zh-tw/index.html
src/i18n/zh-tw/layout/page.html
src/i18n/zh/index.html
src/i18n/zh/layout/page.html

Closes #301
The change in `src/i18n/en/index.html` and `src/i18n/en/layout/page.html` was applied to all languages, they just weren't formatted previously.

Remember current page on language change

---

src/i18n/en/docs/elm.md

small typo

---

src/i18n/en/docs/api.md

Add bundler option `bundleNodeModules`

---

src/i18n/en/docs/typeScript.md

Typescript: add file name to tsconfig.json snippet

---

src/i18n/en/docs/coffeeScript.md

Copied some information about it from it's homepage. This is one step closer to filling in all those pesky language sections! :smiley:

Added more info to the CoffeeScript section

---

src/assets/home.css

Add padding for lang dropdown

---

src/i18n/en/docs/api.md

See https://github.com/parcel-bundler/parcel/issues/2476
The description appeared to be incorrect in the docs

Fix bundled event description

---

src/i18n/en/docs/javascript.md

Adding `--dev` so we save `@babel/preset-react` as a devDependency.

Save @babel/preset-react as a devDependency

---

src/i18n/ja/docs/assets.md
src/i18n/ja/layout/page.html

Hello! I translated `assets.md` to Japanese.
@inductor 
Would you review this PR ? thanks!

Translate "Assets" to Japanese

---

src/i18n/en/docs/vue.md

Add vuejs docs

---

src/i18n/zh-tw/docs/api.md
src/i18n/zh-tw/docs/cli.md
src/i18n/zh-tw/docs/getting_started.md
src/i18n/zh-tw/docs/javascript.md
src/i18n/zh-tw/docs/stylus.md

Sync changes from 0f54198f0da8aaf75852e05a12b9bcd4d5cf2b94 to ef9c4579cdca9615e8e67d77047e898ec15afede.

[zh-tw] Sync translation

---

src/i18n/en/docs/cli.md

Add --no-content-hash in cli doc

---

src/i18n/en/docs/elm.md

Otherwise we hit https://github.com/NoRedInk/find-elm-dependencies/issues/11

elm.md: get HMR to work with the example

---

src/i18n/en/docs/pug.md

Add multiple pug setup examples including how to use locals too

update pug doc

---

src/i18n/en/docs/pug.md

so sorry. I ran into some false positives using locals here.  I can whip up a test repo to prove this if necessary.

update pug LOCALS documentation

---

src/i18n/en/docs/vue.md

Also adjusted the writing style to be consistent with the other pages
Closes #403

Fix vue example

---

src/i18n/ja/docs/transforms.md

Hello! I translated transforms.md to Japanese.
@inductor
Would you review this PR ? thanks! 🙏

translate transforms.md to Japanese

---

src/i18n/en/docs/api.md
src/i18n/fr/docs/api.md
src/i18n/it/docs/api.md
src/i18n/ja/docs/api.md
src/i18n/ko/docs/api.md
src/i18n/pt/docs/api.md
src/i18n/ru/docs/api.md
src/i18n/uk/docs/api.md
src/i18n/zh-tw/docs/api.md
src/i18n/zh/docs/api.md

Defaults to `/`: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Bundler.js#L100
Full disclaimer: out of these languages, I only know English and Italian

Fix publicUrl default value

---

src/i18n/ja/docs/hmr.md

Hi!
I translated hmr.md to Japanese.
If there is anyone who understands Japanese translation, welcome to review :pray:

Translate "HMR" to Japanese

---

src/i18n/en/docs/cli.md

Closes https://github.com/parcel-bundler/website/issues/413

Update detailed report

---

src/i18n/ru/layout/page.html

Found untranslated english bit and translated it to russian

Improved russian translation

---

src/i18n/en/docs/reasonML.md

This PR updates ReasonML React section of ReasonML documentation page to reflect latest changes in ReasonReact library that can be viewed in this blogpost - https://reasonml.github.io/reason-react/blog/2019/04/10/react-hooks

Update example for ReasonML React

---

src/i18n/en/docs/cli.md

https://spectrum.chat/parcel/general/parcel-cli-target-node-includes-devdependencies~f43c7a1a-3735-4557-a997-a0da1d725c57

Remove wrong statement concerning target

---

src/i18n/en/docs/html.md

doc(html): JS import and IE11 support

---

src/i18n/en/docs/scss.md

Added basic example for including SCSS file directly in HTML file.

Added SCSS include example for HTML files.

---

src/i18n/en/docs/recipes.md

brings it inline with JavaScript

Minor capitalization change for TypeScript

---

src/i18n/en/docs/recipes.md

Added a recipe which includes Bootstrap and FontAwesome.
I felt that it might be worthwhile to have instructions for both the compiled and source Bootstrap styles, since customizing the styles means using scss.
Resolves #467

Add recipe for "Bootstrap + FontAwesome"

---

README.md

The branding for ZEIT is all uppercase letters

Fix ZEIT Now casing

---

src/i18n/en/docs/html.md

Add htmlnano documentation

---

src/i18n/ru/docs/html.md
src/i18n/ru/layout/page.html

Translation into Russian article on assets HTML

Translation into Russian

---

src/i18n/ko/docs/graphQL.md
src/i18n/ko/docs/vue.md

1. Add vue page in Korean
2. Add graphQL page in Korean

Add vue, graphQL page in Korean

---

src/i18n/en/docs/openGL.md

We aren't teaching WebGL here, but what Parcel enables you to do compared to plain GLSL.

A more useful GLSL example

---

src/i18n/ja/docs/code_splitting.md

Hello.
I translated [code_spliting page](https://parceljs.org/code_splitting.html) 🙏
Thank you for review or looking my PR 👍

Translate "code_splitting" to Japanese

---

src/assets/style.css
src/i18n/en/layout/page.html

Add note about Parcel 2 docs

---

src/i18n/en/docs/env.md

I had issues getting the environment variables to work, this will probably help someone else too.

Add note about process in relation to env vars

---

src/i18n/ja/docs/production.md

- I translated [production](https://parceljs.org/production.html) page 😺

[ja] Translate "production" to Japanese

---

src/i18n/ja/docs/cli.md

- import English version updates
- I translated [production](https://parceljs.org/cli.html) page ✏️

[ja] Translate "cli" to Japanese

---

src/i18n/ja/docs/recipes.md

- import English version updates
- I translated [recipes](https://parceljs.org/recipes.html) page ✏️

[ja] Translate "recipes" to Japanese 

---

src/i18n/es/docs/getting_started.md
src/i18n/es/layout/page.html

Spanish docs are very outdated and incomplete.
I have translated some spanish things (they are based in the english version):
* Translated missing content in `Getting Started`
* Added Store button in navigation bar
* Added Parcel 2 note in navigation bar
* Reorganized the sidemenu

Improved Spanish docs

---

src/i18n/ja/docs/env.md
src/i18n/ja/layout/page.html

- import English version updates
- I translated [Environment Variables](https://parceljs.org/env.html) page ✏️

[ja] Translate "Environment Variables" into Japanese

---

src/i18n/pt/docs/scss.md

Adding translations for adding with Yarn, importing SCSS directly on HTML and configuring output.

Translating missing info to PT-BR

---

package.json
src/_includes/doc-nav-toggle.js
src/_includes/layout.njk
src/doc-styles.scss
src/features/features.json
src/src.json

This PR adds a basic breakpoint for tablets (which should also somewhat work for mobile)
It also tweaks styling slightly on larger devices and some super minor bugfixes in styling

Styling tweaks and basic mobile support

---

README.md
src/_includes/layout.njk

add docsearch for v2

---

src/assets/style.css
src/i18n/en/layout/page.html

This will probably not be deployed automatically upon merging?

Link to Parcel 2 docs

---

src/getting-started/migration.md

`*` in the pipeline overwrote all of the existing default config...

Fix migration for `url:`

---

src/getting-started/webapp.md

This is a work in progress PR for the getting started page for a generic webapp.
Close T-529

[T-529] Getting started generic webapp

---

src/getting-started/webapp.md

Change TS => TSX in Getting Started WebAPP

---

src/configuration/package-json.md
src/features/module-resolution.md

Documents the behavior of global aliases and externals (which were parcel-bundler/parcel#4853 and parcel-bundler/parcel#4072 respectively).

Document global alias and externals
